name: hello

on:
  push:            # триггер — при каком событии запускать
    branches: '**'

jobs:
  hello:
    runs-on: ubuntu-latest   # напр. ubuntu-latest
    steps:
      - name: echo
        run: echo 'hey there'